version: '3.8'
services:
  frontend:
    container_name: ayaz-memster-frontend
    restart: always
    image: ghcr.io/ayaz-memster/frontend:${IMAGE_VERSION}
    pull_policy: always
    ports:
      - 9500:9500
    labels:
      - traefik.http.routers.ayaz-memster-frontend.rule=Host(`ayaz-memster.okinazuno.me`)
      - traefik.http.routers.ayaz-memster-frontend.tls=true
      - traefik.http.routers.ayaz-memster-frontend.tls.certresolver=letsEncrypt
      - traefik.http.services.ayaz-memster-frontend.loadbalancer.server.port=9500

networks:
  default:
    external: true
    name: traefik-network
